#!/bin/bash
#  Copyright (c) 2010, tummy.com, ltd., All Rights Reserved.
#  Written by Kyle Anderson, tummy.com, ltd.
#  Under the GPL v2 License
#  Modified by Devendran for PWS-1K62P-1R Power Supply

# check for plugin directory where utils.sh lives
[ -d /usr/lib/nagios/plugins ]   && UTILPATH=/usr/lib/nagios/plugins
[ -d /usr/lib64/nagios/plugins ] && UTILPATH=/usr/lib64/nagios/plugins

#  load states and strings
if [ -x "$UTILPATH"/utils.sh ]; then
    . "$UTILPATH"/utils.sh
else
    echo "ERROR: Cannot find utils.sh"
    exit
fi

if ! which ipmitool >/dev/null 2>&1; then
    echo "ERROR: ipmitool missing"
    exit $STATE_UNKNOWN
fi

if [ "$1" == "" ] ; then
  echo "ERROR: no power supply specified"
  exit $STATE_UNKNOWN
fi

case "$1" in

1)
    ps_val="0x70"
    pm_val="0x78"
    ;;
2)
    ps_val="0x72"
    pm_val="0x7a"
    ;;
3)
    ps_val="0x74"
    pm_val="0x7c"
    ;;
*)
   echo "ERROR: no valid power supply specified"
   exit $STATE_UNKNOWN
   ;;
esac

POWER=`sudo /usr/bin/ipmitool raw 0x06 0x52 0x07 ${ps_val} 0x01 0x0c 2>/dev/null`
PMPOWER=`sudo /usr/bin/ipmitool raw 0x06 0x52 0x07 ${pm_val} 0x01 0x78 2>/dev/null`

if [ "$POWER" == " 01" ] && [ "$PMPOWER" == " 01" ]; then
    echo "OK: Power supply $1 OK"
    exit $STATE_OK
elif [ "$POWER" != " 01" ] || [ "$PMPOWER" != " 01" ]; then
    echo "WARNING: Power Supply $1 failure"
    exit $STATE_WARNING
elif [ "$POWER" != " 01" ] && [ "$PMPOWER" != " 01" ]; then
    echo "CRITICAL: Power Supply $1 failure"
    exit $STATE_CRITICAL
fi
